services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-schema.sql:/docker-entrypoint-initdb.d/01-db-schema.sql
      # - ./db-sample.sql:/docker-entrypoint-initdb.d/02-db-sample.sql
    environment:
      - POSTGRES_USER=prowo
      - POSTGRES_PASSWORD=prowo
  adminer:
    image: adminer
    ports:
      - 8081:8080
