version: "3.9"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Test123$
  adminer:
    image: adminer
    ports:
      - 8081:8080
