name: Publish

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/publish.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4.1.5

      - name: Initialize
        run: ./init.sh
        
      - name: Build tailwind
        run: ./build-tailwind.sh

      - name: Run tests
        run: dotnet test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log in to container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: docker.io
          username: ${{ secrets.PROWOCA_REGISTRY_USERNAME }}
          password: ${{ secrets.PROWOCA_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: johannesegger/prowo:${{ github.sha }}
          file: ./Prowo.WebAsm/Server/Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROWOCA_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v2.0.0
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n prowo-ca -g rg-prowo --server docker.io --username '${{ secrets.PROWOCA_REGISTRY_USERNAME }}' --password '${{ secrets.PROWOCA_REGISTRY_PASSWORD }}'
            az containerapp update -n prowo-ca -g rg-prowo --image docker.io/johannesegger/prowo:${{ github.sha }}
